# Generated by Django 5.2.8 on 2025-12-03 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reputaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del cliente')),
                ('texto', models.TextField(verbose_name='Comentario')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1 ★'), (2, '2 ★'), (3, '3 ★'), (4, '4 ★'), (5, '5 ★')], verbose_name='Estrellas')),
                ('origen', models.CharField(blank=True, max_length=50, verbose_name='Origen')),
                ('publicar', models.BooleanField(default=False, verbose_name='¿Publicar en el sitio?')),
            ],
            options={
                'verbose_name': 'Reputación',
                'verbose_name_plural': 'Reputaciones',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ReviewPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='reviews/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
