# Generated by Django 5.2.13 on 2026-04-24 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='bokun_widget_url',
            field=models.URLField(blank=True, help_text='El data-src del widget. Ej: https://widgets.bokun.io/online-sales/.../experience/1175368?partialView=1', null=True, verbose_name='URL del widget de Bókun'),
        ),
    ]
