# Generated by Django 5.2.13 on 2026-04-29 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_tour_bokun_widget_url'),
        ('promotions', '0003_trackinglink_custom_url_trackinglink_tour_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tour',
        ),
    ]
