# Generated by Django 5.2.9 on 2026-04-07 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_newslettersubscriber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newslettersubscriber',
            name='name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
