# Generated by Django 5.2.13 on 2026-04-24 00:39

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre interno')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('tipo', models.CharField(choices=[('partner_tour', 'Partner + Tour específico'), ('partner_all', 'Partner + Todos los tours'), ('tour_all', 'Tour + Todos los partners'), ('global', 'Promoción global')], max_length=20, verbose_name='Tipo')),
                ('vigencia_desde', models.DateField(verbose_name='Vigente desde')),
                ('vigencia_hasta', models.DateField(blank=True, null=True, verbose_name='Vigente hasta')),
                ('limite_usos', models.PositiveIntegerField(blank=True, help_text='Dejar vacío para uso ilimitado.', null=True, verbose_name='Límite de usos')),
                ('usos_actuales', models.PositiveIntegerField(default=0, verbose_name='Usos actuales')),
                ('prioridad', models.PositiveSmallIntegerField(default=10, help_text='Mayor número = mayor prioridad cuando varias promos califican.', verbose_name='Prioridad')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('activa', 'Activa'), ('pausada', 'Pausada'), ('vencida', 'Vencida')], default='borrador', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Promoción',
                'verbose_name_plural': 'Promociones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Identificador corto único, ej: HTL001, REST005, BLG002', max_length=20, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('tipo', models.CharField(choices=[('hotel', 'Hotel'), ('apartamento', 'Apartamento turístico'), ('restaurante', 'Restaurante'), ('bar', 'Bar / Café'), ('tienda', 'Tienda / Souvenir'), ('concierge', 'Concierge / Guía'), ('agencia', 'Agencia de viajes'), ('blogger', 'Blogger / Influencer'), ('evento', 'Evento / Festival'), ('otro', 'Otro')], default='hotel', max_length=20, verbose_name='Tipo')),
                ('contacto_nombre', models.CharField(blank=True, max_length=150, verbose_name='Contacto')),
                ('contacto_email', models.EmailField(blank=True, max_length=254, verbose_name='Email de contacto')),
                ('contacto_telefono', models.CharField(blank=True, max_length=50, verbose_name='Teléfono')),
                ('sitio_web', models.URLField(blank=True, verbose_name='Sitio web')),
                ('direccion', models.CharField(blank=True, max_length=255, verbose_name='Dirección')),
                ('notas', models.TextField(blank=True, verbose_name='Notas internas')),
                ('comision_default', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Comisión que recibe el partner por reserva. Puede sobrescribirse por promoción.', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Comisión por defecto (%)')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Partner',
                'verbose_name_plural': 'Partners',
                'ordering': ['nombre'],
                'indexes': [models.Index(fields=['tipo', 'activo'], name='promotions__tipo_46ddcb_idx')],
            },
        ),
        migrations.CreateModel(
            name='TrackingLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal', models.CharField(choices=[('qr', 'QR físico'), ('web_link', 'Link web'), ('widget', 'Widget embebido')], max_length=20, verbose_name='Canal')),
                ('codigo', models.CharField(help_text='Slug que aparece en la URL pública.', max_length=20, unique=True, verbose_name='Código URL')),
                ('qr_image', models.ImageField(blank=True, null=True, upload_to='promotions/qr/', verbose_name='Imagen QR')),
                ('notas', models.CharField(blank=True, max_length=255, verbose_name='Notas internas')),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('partner', models.ForeignKey(help_text='Partner concreto al que se entregó este material.', on_delete=django.db.models.deletion.CASCADE, related_name='tracking_links', to='promotions.partner')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_links', to='promotions.promotion')),
            ],
            options={
                'verbose_name': 'Link de tracking',
                'verbose_name_plural': 'Links de tracking',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromotionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descuento_pct', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Descuento (%)')),
                ('comision_partner_pct', models.DecimalField(blank=True, decimal_places=2, help_text='Si vacío, usa la comisión por defecto del partner.', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Comisión partner (%)')),
                ('partner', models.ForeignKey(blank=True, help_text='Vacío = aplica a todos los partners.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotion_rules', to='promotions.partner')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='promotions.promotion')),
                ('tour', models.ForeignKey(blank=True, help_text='Vacío = aplica a todos los tours.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotion_rules', to='landing.tour')),
            ],
            options={
                'verbose_name': 'Regla de promoción',
                'verbose_name_plural': 'Reglas de promoción',
                'constraints': [models.UniqueConstraint(fields=('promotion', 'partner', 'tour'), name='unique_rule_per_promotion')],
            },
        ),
        migrations.CreateModel(
            name='Redemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bokun_booking_id', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='ID reserva Bókun')),
                ('monto_bruto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto bruto')),
                ('descuento_pct_aplicado', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Descuento aplicado (%)')),
                ('descuento_monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto descontado')),
                ('monto_neto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto neto cobrado')),
                ('comision_partner_pct', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Comisión partner (%)')),
                ('comision_partner_monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Comisión partner ($)')),
                ('cliente_nombre', models.CharField(blank=True, max_length=200)),
                ('cliente_email', models.EmailField(blank=True, max_length=254)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de pago a partner'), ('confirmada', 'Reserva confirmada'), ('pagada', 'Comisión pagada'), ('cancelada', 'Cancelada')], default='confirmada', max_length=20)),
                ('notas', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pagada_at', models.DateTimeField(blank=True, null=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redemptions', to='promotions.partner')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redemptions', to='promotions.promotion')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redemptions', to='landing.tour')),
                ('tracking_link', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redemptions', to='promotions.trackinglink')),
            ],
            options={
                'verbose_name': 'Redención',
                'verbose_name_plural': 'Redenciones',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['partner', 'created_at'], name='promotions__partner_1699dd_idx'), models.Index(fields=['tour', 'created_at'], name='promotions__tour_id_183008_idx'), models.Index(fields=['estado'], name='promotions__estado_967f63_idx')],
            },
        ),
    ]
