# Generated by Django 5.2.13 on 2026-04-29 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('image', models.ImageField(upload_to='tours/')),
                ('button_text', models.CharField(default='VER JORNADA', max_length=100)),
                ('button_url', models.URLField(blank=True, null=True)),
                ('bokun_widget_url', models.URLField(blank=True, help_text='El data-src del widget. Ej: https://widgets.bokun.io/online-sales/.../experience/1175368?partialView=1', null=True, verbose_name='URL del widget de Bókun')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
