# Generated by Django 5.2.13 on 2026-04-29 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0002_tour'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackinglink',
            name='custom_url',
            field=models.URLField(blank=True, help_text='Si se define, tiene prioridad sobre el tour', null=True),
        ),
        migrations.AddField(
            model_name='trackinglink',
            name='tour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='promotions.tour'),
        ),
        migrations.AlterField(
            model_name='promotionrule',
            name='tour',
            field=models.ForeignKey(blank=True, help_text='Vacío = aplica a todos los tours.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotion_rules', to='promotions.tour'),
        ),
        migrations.AlterField(
            model_name='redemption',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redemptions', to='promotions.tour'),
        ),
        migrations.AlterField(
            model_name='trackinglink',
            name='promotion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracking_links', to='promotions.promotion'),
        ),
    ]
