# Generated by Django 5.2.13 on 2026-04-29 21:35

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0003_trackinglink_custom_url_trackinglink_tour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redemption',
            name='comision_partner_monto',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Comisión partner ($)'),
        ),
        migrations.AlterField(
            model_name='redemption',
            name='comision_partner_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Comisión partner (%)'),
        ),
        migrations.AlterField(
            model_name='redemption',
            name='descuento_monto',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Monto descontado'),
        ),
        migrations.AlterField(
            model_name='redemption',
            name='descuento_pct_aplicado',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Descuento aplicado (%)'),
        ),
        migrations.AlterField(
            model_name='redemption',
            name='promotion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='redemptions', to='promotions.promotion'),
        ),
        migrations.AlterField(
            model_name='trackinglink',
            name='promotion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tracking_links', to='promotions.promotion'),
            preserve_default=False,
        ),
    ]
