# Generated by Django 5.2.13 on 2026-04-29 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0004_alter_redemption_comision_partner_monto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='clics',
            field=models.PositiveIntegerField(default=0, verbose_name='Clics / Scans'),
        ),
    ]
