# Generated by Django 5.2.13 on 2026-04-29 22:18

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0005_promotion_clics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion',
            name='clics',
        ),
        migrations.RemoveField(
            model_name='trackinglink',
            name='custom_url',
        ),
        migrations.AddField(
            model_name='trackinglink',
            name='clics',
            field=models.PositiveIntegerField(default=0, verbose_name='Scans / Clics'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='codigo',
            field=models.CharField(help_text='Identificador corto único, ej: HTL001, REST005', max_length=20, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='comision_default',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Comisión por defecto (%)'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='limite_usos',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Límite de usos'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='prioridad',
            field=models.PositiveSmallIntegerField(default=10, verbose_name='Prioridad'),
        ),
        migrations.AlterField(
            model_name='promotionrule',
            name='comision_partner_pct',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Comisión partner (%)'),
        ),
        migrations.AlterField(
            model_name='promotionrule',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotion_rules', to='promotions.partner'),
        ),
        migrations.AlterField(
            model_name='promotionrule',
            name='tour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotion_rules', to='promotions.tour'),
        ),
        migrations.AlterField(
            model_name='redemption',
            name='promotion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redemptions', to='promotions.promotion'),
        ),
        migrations.AlterField(
            model_name='trackinglink',
            name='canal',
            field=models.CharField(choices=[('qr', 'QR físico'), ('web_link', 'Link web'), ('widget', 'Widget embebido')], default='qr', max_length=20, verbose_name='Canal'),
        ),
        migrations.AlterField(
            model_name='trackinglink',
            name='codigo',
            field=models.CharField(max_length=20, unique=True, verbose_name='Código URL'),
        ),
        migrations.AlterField(
            model_name='trackinglink',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_links', to='promotions.partner'),
        ),
        migrations.AlterField(
            model_name='trackinglink',
            name='promotion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracking_links', to='promotions.promotion'),
        ),
        migrations.AlterField(
            model_name='trackinglink',
            name='tour',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tracking_links', to='promotions.tour'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='trackinglink',
            constraint=models.UniqueConstraint(fields=('partner', 'tour', 'canal'), name='unique_tracking_per_partner_tour_canal'),
        ),
    ]
