# Generated by Django 5.2.13 on 2026-05-04 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0006_remove_promotion_clics_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='bokun_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='ID en Bókun'),
        ),
        migrations.AddField(
            model_name='tour',
            name='bokun_synced_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última sync con Bókun'),
        ),
    ]
