# Generated by Django 5.2.13 on 2026-05-04 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0007_bokun_sync_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='bokun_image_url',
            field=models.URLField(blank=True, null=True, verbose_name='Imagen (URL Bókun)'),
        ),
        migrations.AddField(
            model_name='tour',
            name='duration',
            field=models.CharField(blank=True, max_length=100, verbose_name='Duración'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tours/'),
        ),
    ]
