# Generated by Django 5.2.13 on 2026-05-04 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0008_bokun_image_url_and_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Tour principal (destacado)'),
        ),
    ]
